### ISSUE TITLE
Grosses Dankeschön

### ISSUE THREAD

**Issue by Mannshoch** [lorenzschmid/wp-imapauth#6]
Danke! für das Plugin. Damit habe ich jetzt die Userverwaltung für Wordpress und Owncloud wunderbar über eine E-Mail Adresse lösen können.

**Comment by lorenzschmid** [comment]
Danke für das Feedback! Das Plugin überwache ich zur Zeit nicht mehr, aber ich werde es mir in naher Zukunft wohl mal wieder genauer anschauen.
