### ISSUE TITLE
[Frage] Benutzername muss ganze adresse sein

### ISSUE THREAD

**Issue by Mannshoch** [lorenzschmid/wp-imapauth#7]
Hi
Ich wechsle gerade den hoster und habe gemerkt, dass es zwischen der eigenen testumgebung und dem hoster einen unterschied gibt. Am neuen Ort muss der Benutzername die vollständige e-Mail adresse sein.  In meiner Testumgebung reichte der Text vor dem @ 

Kann es sein, dass das Plugin an diesem neuen Ort aus diesem Grund nichtmehr funktioniert?

[edit]
hab das selbe Problem mit der Owncloud.
Hier mein Ticket bei Owncloud: https://github.com/owncloud/apps/issues/2175

**Comment by lorenzschmid** [comment]
Vorneweg vielleicht soviel, ich entwickle das Plugin zur Zeit nicht aktiv weiter. Dies deshalb weil ich mir in der Zwischenzeit ein wesentlich flexibleres Plugin geschrieben habe ([wp-extauth](https://github.com/lorenzschmid/wp-extauth)). Dieses Plugin wird dir allerdings wahrscheinlich nicht genügen, deshalb hier ein paar Punkte, die dir vielleicht weiter helfen können:

1. Wie funktioniert die Authentifizierung mit deinem IMAP Server? Diese verlangen zum Teil nur den Benutzername und nicht die ganze Adresse. Das könnte den Unterschied zwischen lokaler und Produktionsumgebung ausmachen, den du nun auch mit ownCloud siehst. (Das Plugin unterstützt übrigens nur eine Anmeldung mit der ganzen Adresse)
2. Auf der Einstellungsseite des Plugins gibt es die Option "User Suffix", dieser wird zusammen mit einem @ automatisch an die Eingabe des Users angehängt, wenn dieser keine vollständige Email-Adresse (mit einem @) angibt. Vielleicht hast du diesen auf deinem neuen Hoster (noch) nicht gesetzt.

**Comment by Mannshoch** [comment]
Danke für den Hinweis. wenn es möglich ist, möchte ich schon alles über die E-Mail adresse machen. Es macht die Verwaltung unserer Vereinshomepage viel einfacher - wenns den läuft.

Kannst du mir vielleicht sagen, wie ich an die Fehlermeldung eines gescheiterten Logins komme? Ich stochere bei der Ursachensuche zur Zeit im Dunkeln herum und das Server errorlog scheint kaum Informationen zu enthalten.

**Comment by lorenzschmid** [comment]
Ich hab soeben eine kleine Logging Funktion ins Plugin eingebunden. Diese sollte es dir ermöglichen, mehr über die aktuelle Ursache zu erfahren. Gehe dazu wie folgt vor:
1. Lade die aktualisierte Datei (`imapauth.php`) des Plugins direkt hier von Github herunter
2. Aktiviere die Debugging-Funktion von Wordpress wie [hier](https://www.smashingmagazine.com/2011/03/ten-things-every-wordpress-plugin-developer-should-know/#how-to-enable-debugging) beschrieben.
3. Versuche dich einzulogen
4. Beobachte die Ausgabe im Log-File unter `wp-content/debug.log`

**Comment by Mannshoch** [comment]
Hi vielen Dank dafür. Habe herausgefunden, dass ich hier Localhost nutzen muss um mich zu verbinden. Die nachfolgenden Fehlermeldungen habe ich wärend dessen in Wordpress erhalten. 

Beim aktivieren des Plugins erhalte ich:

> Notice: has_cap wurde mit einem Parameter oder Argument aufgerufen, der seit Version 2.0 veraltet ist! Die Benutzung von user_level in Plugins und Themes ist veraltet. Nutze stattdessen das Abfragen von roles oder capabilities. in /xxx/WEB/wp-includes/functions.php on line 3842

Beim Speichern der einstellung auf der einstellungsseite "Änderung übernehmen" Ich dachte anfangs, dass wegen der Fehlerseite die Einstellungen nicht gespeichert wurden, aber das scheint doch der Fall gewesen zu sein: 

> Notice: has_cap wurde mit einem Parameter oder Argument aufgerufen, der seit Version 2.0 veraltet ist! Die Benutzung von user_level in Plugins und Themes ist veraltet. Nutze stattdessen das Abfragen von roles oder capabilities. in /xxx/WEB/wp-includes/functions.php on line 3842
> 
> Notice: options.php wurde mit einem Parameter oder Argument aufgerufen, der seit Version 2.7 veraltet ist! Die Einstellung imapauth_mailbox ist nicht in WordPress registriert. Unregistrierte Einstellungen werden offiziell nicht unterstüzt. Details erfährst du unter https://codex.wordpress.org/Settings_API in /xxx/WEB/wp-includes/functions.php on line 3842
> 
> Notice: options.php wurde mit einem Parameter oder Argument aufgerufen, der seit Version 2.7 veraltet ist! Die Einstellung imapauth_pad_domain ist nicht in WordPress registriert. Unregistrierte Einstellungen werden offiziell nicht unterstüzt. Details erfährst du unter https://codex.wordpress.org/Settings_API in /xxx/WEB/wp-includes/functions.php on line 3842
> 
> Notice: options.php wurde mit einem Parameter oder Argument aufgerufen, der seit Version 2.7 veraltet ist! Die Einstellung impauth_create_new ist nicht in WordPress registriert. Unregistrierte Einstellungen werden offiziell nicht unterstüzt. Details erfährst du unter https://codex.wordpress.org/Settings_API in /xxx/WEB/wp-includes/functions.php on line 3842
> 
> Warning: Cannot modify header information - headers already sent by (output started at /xxx/WEB/wp-includes/functions.php:3842) in /xxx/WEB/wp-includes/pluggable.php on line 1171

In der Debug log steht folgendes, und dass hatmich auf die Idee gebracht, einmal localhost aus zu probieren:

> [04-May-2016 15:21:10 UTC] [wp-imapauth] Login failed! User: test@xxxxx.ch, Error: No such host as yyyyy.yyyyy.ch
> [04-May-2016 15:21:10 UTC] PHP Notice:  Unknown: No such host as yyyyy.yyyyy­.ch (errflg=2) in Unknown on line 0

Es ist da aber erstaunlich, dass in Owncloud das Webmail App funktioniert, da habe ich auch nicht localhost für den Imap zugriff verwendet.

Vielen Dank nocheinmal
Mannshoch.

**Comment by lorenzschmid** [comment]
Gern geschehen, super wenn es läuft. Noch kurz ein Kommentar zu den vielen PHP Notices, diese stammen vom Wordpress Core und haben nichts mit dem Plugin zu tun.

**Comment by Mannshoch** [comment]
Danke für die Info. Heisst also, dass Wordpress zu sich selber inkompatibel ist :-).
Ich habe mich einfach über die Meldungen gewundert, dass einige imapauth Funktionen nicht registriert seien. Freue mich aber natürlich dass dennoch alles funktioniert.

**Comment by lorenzschmid** [comment]
Du hast recht, die Meldungen betreffen doch das Plugin. Ich habe die Meldungen zu schnell überflogen. Vermute allerdings das das vorerst kein Problem sein soll.
